<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="6" hostname="LAPTOP-FR81P7PN" name="com.testng.concepts.SampleTest" tests="7" failures="0" timestamp="2020-05-17T17:28:16 IST" time="0.027" errors="1">
  <testcase name="Test1" time="0.001" classname="com.testng.concepts.SampleTest">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.001" classname="com.testng.concepts.SampleTest">
    <error type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at com.testng.concepts.SampleTest.Test1(SampleTest.java:14)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:204)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.001" classname="com.testng.concepts.SampleTest">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.001" classname="com.testng.concepts.SampleTest">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.001" classname="com.testng.concepts.SampleTest">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.020" classname="com.testng.concepts.SampleTest">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.002" classname="com.testng.concepts.SampleTest">
    <skipped/>
  </testcase> <!-- Test1 -->
</testsuite> <!-- com.testng.concepts.SampleTest -->
